
spring.application.name=resume-screener
# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resume_screener}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:resume_screener}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# App
server.port=${PORT:8081}
#jwt
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:900000}
# Redis configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
ml.service.url=${ML_SERVICE_URL:http://localhost:8000}
#Smtp configuration
spring.mail.host=${SPRING_MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${SPRING_MAIL_PORT:2525}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#RabbitMQ configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
spring.rabbitmq.ssl.enabled=${SPRING_RABBITMQ_SSL_ENABLED:false}